# SPDX-FileCopyrightText: 2026 Carmine Varriale <C.varriale@tudelft.nl>
# SPDX-FileCopyrightText: 2026 Federico Angioni <F.angioni@student.tudelft.nl>
# SPDX-FileCopyrightText: 2026 Maarten van Hoven <M.B.vanHoven@tudelft.nl>
#
# SPDX-License-Identifier: Apache-2.0
import marimo

__generated_with = "0.19.11"
app = marimo.App(width="medium")

with app.setup:
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path.cwd()))

    # Initialization code that runs before all other cells
    import marimo as mo

    # Import dependencies
    from core import _defaults
    from plotly.subplots import make_subplots
    import plotly.graph_objects as go
    import plotly.express as px
    import numpy as np
    from core import aircraft as ac

    # Set local/online filepath
    _defaults.FILEURL = _defaults.get_url()

    # Plotly dark mode template
    _defaults.set_plotly_template()

    # Data directory
    data_dir = str(
        mo.notebook_location().parent.parent / "data" / "AircraftDB_Standard.csv"
    )


@app.cell
def _():
    # Set navbar on the right
    _defaults.set_sidebar()
    return


@app.cell
def _():
    mo.md(r"""
    # Optimization Methodologies

    In these series of notebooks, we are going to explore different optimization methodologies that can be used to solve performance optimization problems for aircraft.
    We will start from a simple problem (that you may have already encountered), and solve it with mathematical tools that you may already be familiar with.
    We will then progressively complicate the problem by including constraints and variable dependencies, and explore the application of more general optimization approaches.

    The following notebooks will cover:

    1. Optimization of a continuous function of 1 variable on a compact domain, by finding its interior stationary points and evaluating boundary values.
    2. Optimization of a continuous function of 2 variables on a compact domain, by finding its interior stationary points and evaluating boundary values.
    3. Optimization of a function of 2 variables subjected to equality constraints
        1. By substituting the constraint expression in the function
        2. By using Lagrange multipliers.
    4. Optimization of a function of 2 variables with both equality and inequality constrains, by means of KKT analysis.

    In order to keep the focus on the optimization methodologies, we will use the same objective function: the aerodynamic efficiency.
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Aerodynamic Efficiency
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.callout(
        mo.md(
            r"""
    The aerodynamic efficiency $E$ expresses the ratio between the lift force $L$ generated by the aircraft in a certain flight condition and the corresponding drag force $D$ generated in the same condition. From the definition of lift and drag coefficients, the aerodynamic efficiency is also the ratio between the lift coefficient $C_L$ and the drag coefficient $C_D$

    $$E = \frac{L}{D} = \frac{\frac{1}{2}\rho V^2 S C_L}{\frac{1}{2}\rho V^2 S C_D} = \frac{C_L}{C_D}$$

    """
        )
    ).center().style({"text-align": "center"})
    return


@app.cell
def _():
    mo.md(r"""
    The lift coefficient expresses the capability of the aircraft to generate aerodynamic lift for a given angle of attack and flow regime.
    The drag coefficient expresses the capability of the aircraf to generate aerodynamic drag for a given angle of attack and flow regime.

    Both these coefficients express what the air does to the aircraft, when flying around it at a given angle of attack.
    **This has nothing to do with flight performance.**
    The aircraft experiences a certain airspeed and angle of attack also when sitting on a windy runway, being transported on the landing deck of a carrier ship, or simply falling down from the sky.

    What these coefficients express is therefore not a _flight_ performance metric, but rather an _aerodynamic_ performance metric.
    Aerodynamic performance is still very useful, of course, as it plays a major role in the analysis and interpretation of flight performance.
    """)
    return


@app.cell
def _():
    mo.md(r"""
    In the following notebooks, we are going to assume different models to express the drag coefficients as a function of the lift coefficient (but not only), in order to calculate the maximum aerodynamic efficiency using different methods.

    First, we are going to assume it only depends on the lift coefficient using a _parabolic_ drag polar model, then we are going to also assume it depends on the Mach number, in order to see the effects of compressibility.

    Because $E$ is only an aerodynamic performance metric, we will include _flight constraints_ in the optimization problem to make it relevant for scenarios in which the aircraft is actually flying.
    """)
    return


@app.cell
def _():
    _defaults.nav_footer(
        "Problem_Formulation/FlightControls.py",
        "Flight Controls",
        "Optimization_Methodology/UnivariateOptimization.py",
        "Univariate Optimization",
    )
    return


if __name__ == "__main__":
    app.run()
