import marimo

__generated_with = "0.16.5"
app = marimo.App(width="medium")

with app.setup:
    # Initialization code that runs before all other cells
    import marimo as mo

    # Import dependencies
    from core import _defaults
    from plotly.subplots import make_subplots
    import plotly.graph_objects as go
    import plotly.express as px
    import numpy as np
    from core import aircraft as ac


    # Set local/online filepath
    _defaults.FILEURL = _defaults.get_url()

    # Plotly dark mode template
    _defaults.set_plotly_template()

    # Data directory
    data_dir = str(mo.notebook_location() / "public" / "AircraftDB_Standard.csv")


@app.cell
def _():
    # Set navbar on the right
    _defaults.set_sidebar()
    return


@app.cell(hide_code=True)
def _():
    mo.md(
        r"""
    # Aerodynamic Efficiency

    The lift polar expresses the capability of the aircraft to generate aerodynamic lift at a given angle of attack.
    The drag polar expresses the capability of the aircraf to generate aerodynamic drag at a given angle of attack, or, equivalenty, at a given lift coefficient.

    Both these curves express what the air does to the aircraft, when flying around it at a given angle of attack.
    This has nothing to do with flight performance.
    The aircraft experiences a certain airspeed and angle of attack also when sitting on a windy runway, being transported on the landing deck of a carrier ship, or simply falling down from the sky.

    What these curves expressed is therefore not a _flight performance_ metric, but rather an _aerodynamic performance_ metric.
    Aerodynamic performance is still very useful, of course, as it plays a major role in the analysis and interpretation of flight performance.
    """
    )
    return


@app.cell(hide_code=True)
def _():
    mo.callout(
        mo.md(
            r"""
    Aerodynamic efficiency $E$ expresses the ratio between the lift force generated by the aircraft in a certain flight condition and the corresponding drag force generated in the same conditions. From the definition of lift and drag coefficients, the aerodynamic efficiency is also the ratio between the lift coefficient and the drag coefficient

    $$E = \frac{L}{D} = \frac{\frac{1}{2}\rho V^2 S C_L}{\frac{1}{2}\rho V^2 S C_D} = \frac{C_L}{C_D}=\frac{C_L}{C_{D_0}+KC_L^2}$$

    """
        )
    ).center().style({"text-align": "center"})
    return


@app.cell(hide_code=True)
def _():
    mo.md(
        r"""
    ## Boundary values
    Two notable values of the aerodynamic efficiency are easy to calculate, corresponding to the boundary value of $C_L$.

    $$C_L=0 \quad \Rightarrow \quad  E=0$$

    $$C_L=C_{L_\mathrm{max}} \quad \Rightarrow \quad  E_S = \frac{C_{L_\mathrm{max}}}{C_{D_0}+K C_{L_\mathrm{max}}^2}$$

    $E$ is a non monotonic function of the $C_L$, and therefore it is expected that it will have some staionary points inside the domain.
    """
    )
    return


@app.cell
def _():
    data = ac.available_aircrafts(data_dir).loc[
        :,
        [
            "full_name",
            "ID",
            "type",
            "b",
            "S",
            "CD0",
            "K",
            "CLmax_ld",
            "MTOM",
            "OEM",
        ],
    ]
    return (data,)


@app.cell(hide_code=True)
def _(data):
    # Database cell (1)


    ac_table = mo.ui.table(
        data=data,
        pagination=True,
        show_column_summaries=False,
        selection="single",
        initial_selection=[0],
        page_size=4,
        show_data_types=False,
    )

    ac_table
    return (ac_table,)


@app.cell
def _(ac_table, data):
    # Variables declared
    meshgrid_n = 101
    xy_lowerbound = -0.1

    CL_buffer = 1
    # Handle deselected row from table
    if ac_table.value is not None and ac_table.value.any().any():
        active_selection = ac_table.value.iloc[0]
    else:
        active_selection = data.iloc[0]


    CLmax = active_selection["CLmax_ld"]
    CD0 = active_selection["CD0"]
    K = active_selection["K"]

    CL_array = np.linspace(0, CLmax + CL_buffer, meshgrid_n)
    CD_array = CD0 + K * CL_array**2
    E_array = CL_array / (CD0 + K * CL_array**2)
    CL_E = np.sqrt(CD0 / K)
    CD_E = CD0 + K * CL_E**2
    E_max = CL_E / (CD0 + K * CL_E**2)
    E_max_line = CD_E / CL_E * CL_array
    return (
        CD_E,
        CD_array,
        CL_E,
        CL_array,
        CLmax,
        E_array,
        E_max,
        E_max_line,
        active_selection,
    )


@app.cell
def _(
    CD_E,
    CD_array,
    CL_E,
    CL_array,
    CLmax,
    E_array,
    E_max,
    E_max_line,
    active_selection,
):
    fig_endurance = make_subplots(
        rows=1, cols=2, specs=[[{"type": "xy"}, {"type": "xy"}]]
    )


    fig_endurance.add_traces(
        [
            go.Scatter(
                x=CL_array,
                y=CD_array,
                showlegend=True,
                name=r"$C_D$",
                line=dict(color="rgba(0, 114, 178, 1)"),
            ),
            go.Scatter(
                x=CL_array,
                y=E_max_line,
                showlegend=False,
                line=dict(color="rgba(230, 159, 0, 1)", dash="dot"),
            ),
            go.Scatter(
                x=[CL_E],
                y=[CD_E],
                line=dict(color="rgba(240, 228, 66, 1)"),
                mode="markers+text",
                text=[r"${E_{\mathrm{max}}}$"],
                showlegend=False,
                textposition="top left",
            ),
        ],
        cols=1,
        rows=1,
    )

    fig_endurance.add_traces(
        [
            go.Scatter(x=CL_array, y=E_array, name=r"$E$"),
            go.Scatter(
                x=[CL_E],
                y=[E_max],
                name=r"$E_{\mathrm{max}}$",
                marker=dict(color="rgba(240, 228, 66, 1)"),
                text=[r"${E_{\mathrm{max}}}$"],
                mode="markers+text",
                textposition="top left",
            ),
        ],
        cols=2,
        rows=1,
    )

    fig_endurance.add_vline(
        x=CLmax,
        line_dash="dot",
        line_color="red",
        annotation=dict(text=r"$C_{L_{\mathrm{max}}}$", xshift=10, yshift=-10),
        row=1,
        col=1,
    )

    fig_endurance.add_shape(
        type="line",
        x0=CL_E,
        x1=CL_E,
        y0=0,
        y1=CD_E,
        line_dash="dot",
        line_color="rgba(0, 158, 115, 1)",
        row=1,
        col=1,
    )

    fig_endurance.add_shape(
        type="line",
        x0=CL_E,
        x1=CL_E,
        y0=0,
        y1=E_max,
        line_dash="dot",
        line_color="rgba(0, 158, 115, 1)",
        row=1,
        col=2,
    )

    fig_endurance.add_annotation(
        x=CL_E - 0.1, y=0, text=r"$C_{L_E}$", showarrow=False, col=1, row=1
    )
    fig_endurance.add_annotation(
        x=CL_E - 0.1, y=0, text=r"$C_{L_E}$", showarrow=False, col=2, row=1
    )


    fig_endurance.add_annotation(
        x=CL_array[-10],
        y=E_max_line[-10] + 0.09,
        text=r"$\left(\frac{C_D}{C_L}\right)_{\mathrm{max}}$",
        showarrow=False,
        col=1,
        row=1,
    )


    fig_endurance.update_xaxes(title_text=r"$C_L \; (-)$", col=1, row=1)
    fig_endurance.update_yaxes(title_text=r"$C_D \; (-)$", col=1, row=1)
    fig_endurance.update_xaxes(title_text=r"$C_L \; (-)$", col=2, row=1)
    fig_endurance.update_yaxes(title_text=r"$E \; (-)$", col=2, row=1)

    fig_endurance.update_layout(
        title_text=active_selection["full_name"],
        title_x=0.5,
    )
    mo.output.clear()
    return (fig_endurance,)


@app.cell
def _(fig_endurance):
    fig_endurance
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""## Optimization""")
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    Find the maximum aerodynamic efficiency by changing the lift coefficient within certain limits

    $$
    \begin{aligned}
        \max_{C_L} 
        & \quad E=\frac{C_L}{C_D}=\frac{C_L}{C_{D_0}+KC_L^2} \\
        % \text{subject to} 
        % & \quad \bm{c}_\mathrm{eq}(\bm{x},\bm{u}; \bm{p}) = 0 \\
        % & \quad \bm{c_\mathrm{ineq}}(\bm{x},\bm{u}; \bm{p}) \le 0 \\
        \text{for } 
        & \quad C_L \in [0, C_{L_\mathrm{max}}]
    \end{aligned}
    $$

    """).callout().center().style({"text-align": "center"})
    return


@app.cell(hide_code=True)
def _():
    mo.md(
        r"""
    The existence of a stationary point inside the domain or on its boundary is guaranteed by Weierstrass theorem for a contiunoues function in a compact set. 

    The necessary condition for an interior point to be stationary is given by the fact that the gradient of the objective function with respect to the decision variable is zero in that point. 
    Therefore, interior stationary points can be found by equating the gradient of the objecitive function to zero.
    """
    )
    return


@app.cell(hide_code=True)
def _():
    mo.md(
        r"""
    $$ \frac{\mathrm{d}E}{\mathrm{d}C_L} = \frac{C_{D_0}-KC_L^2}{C_{D_0}+KC_L^2} = 0 
    \quad \text{for} \quad C_L = C_{L_E} = \sqrt{\frac{C_{D_0}}{K}} $$
    """
    )
    return


@app.cell(hide_code=True)
def _():
    mo.md(
        r"""
    It can be easily verified that this is indeed a maximum by looking at the convexity of the objective function.
    A sufficient condition to prove it is actually a maximum is to show that the Hessian is negative at the stationary point.
    """
    )
    return


@app.cell(hide_code=True)
def _():
    mo.md(
        r"""
    The value of the total drag coefficient in this condition is twice the value of the zero-lift one, meaning that zero-lift and induced drag have the same contribution to total drag.

    The corresponding value of the maximum aerodynamic efficiency is therefore:

    $$ E_\mathrm{max} = \frac{C_{L_E}}{C_{D_0}+KC_{L_E}^2} = \frac{\sqrt{\frac{C_{D_0}}{K}}}{2C_{D_0}} = \sqrt{\frac{1}{4KC_{D_0}}}$$
    """
    )
    return


@app.cell
def _():
    _defaults.nav_footer(
        "FlightControls.py", "Flight Controls", "MinDrag.py", "Minimum Drag"
    )
    return


if __name__ == "__main__":
    app.run()
