import marimo

__generated_with = "0.13.15"
app = marimo.App(width="medium")

with app.setup:
    # Initialization code that runs before all other cells
    import marimo as mo
    import _defaults

    _defaults.set_plotly_template()


@app.cell
def _():
    _defaults.set_sidebar()
    return


@app.cell
def _():
    mo.md(
        r"""
    # Aerodynamic Efficiency

    The lift polar expresses the capability of the aircraft to generate aerodynamic lift at a given angle of attack.
    The drag polar expresses the capability of the aircraf to generate aerodynamic drag at a given angle of attack, or, equivalenty, at a given lift coefficient.

    Both these curves express what the air does to the aircraft, when flying around it at a given angle of attack.
    This has nothing to do with flight performance.
    The aircraft experiences a certain airspeed and angle of attack also when sitting on a windy runway, being transported on the landing deck of a carrier ship, or simply falling down from the sky.

    What these curves expressed is therefore not a _flight performance_ metric, but rather an _aerodynamic performance_ metric.
    Aerodynamic performance is still very useful, of course, as it plays a major role in the analysis and interpretation of flight performance.
    """
    )
    return


@app.cell
def _():
    mo.callout(
        mo.md(
            r"""
    Aerodynamic efficiency $E$ expresses the ratio between the lift force generated by the aircraft in a certain flight condition and the corresponding drag force generated in the same conditions. From the definition of lift and drag coefficients, the aerodynamic efficiency is also the ratio between the lift coefficient and the drag coefficient

    $$E = \frac{L}{D} = \frac{\frac{1}{2}\rho V^2 S C_L}{\frac{1}{2}\rho V^2 S C_D} = \frac{C_L}{C_D}=\frac{C_L}{C_{D_0}+KC_L^2}$$

    """
        )
    ).center().style({"text-align": "center"})
    return


@app.cell
def _():
    mo.md(
        r"""
    ## Boundary values
    Two notable values of the aerodynamic efficiency are easy to calculate, corresponding to the boundary value of $C_L$.

    $$C_L=0 \quad \Rightarrow \quad  E=0$$

    $$C_L=C_{L_\mathrm{max}} \quad \Rightarrow \quad  E_S = \frac{C_{L_\mathrm{max}}}{C_{D_0}+K C_{L_\mathrm{max}}}$$

    E is a non monotonic function of the $C_L$, and therefore it is expected that it will have some staionary points inside the domain.

    - [ ] Plot CD vs CL, E vs CL.
    - [ ] Indicate with S the stall point and with E the point corresponding the Emax.
    - [ ] On the CD vs CL chart, show the tangent line corresponding to max E
    """
    )
    return


@app.cell
def _():
    mo.md(r"""## Optimization""")
    return


@app.cell
def _():
    mo.md(r"""
    Find the maximum aerodynamic efficiency by changing the lift coefficient within certain limits

    $$
    \begin{aligned}
        \max_{C_L} 
        & \quad E=\frac{C_L}{C_D}=\frac{C_L}{C_{D_0}+KC_L^2} \\
        % \text{subject to} 
        % & \quad \bm{c}_\mathrm{eq}(\bm{x},\bm{u}; \bm{p}) = 0 \\
        % & \quad \bm{c_\mathrm{ineq}}(\bm{x},\bm{u}; \bm{p}) \le 0 \\
        \text{for } 
        & \quad C_L \in [0, C_{L_\mathrm{max}}]
    \end{aligned}
    $$

    """).callout().center().style({"text-align": "center"})
    return


@app.cell
def _():
    mo.md(
        r"""
    The existence of a stationary point inside the domain or on its boundary is guaranteed by Weierstrass theorem for a contiunoues function in a compact set. 

    The necessary condition for an interior point to be stationary is given by the fact that the gradient of the objective function with respect to the decision variable is zero in that point. 
    Therefore, interior stationary points can be found by equating the gradient of the objecitive function to zero.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    $$ \frac{\mathrm{d}E}{\mathrm{d}C_L} = \frac{C_{D_0}-KC_L^2}{C_{D_0}+KC_L^2} = 0 
    \quad \text{for} \quad C_L = C_{L_E} = \sqrt{\frac{C_{D_0}}{K}} $$
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    It can be easily verified that this is indeed a maximum by looking at the convexity of the objective function.
    A sufficient condition to prove it is actually a maximum is to show that the Hessian is negative at the stationary point.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    The value of the total drag coefficient in this condition is twice the value of the zero-lift one, meaning that zero-lift and induced drag have the same contribution to total drag.

    The corresponding value of the maximum aerodynamic efficiency is therefore:

    $$ E_\mathrm{max} = \frac{C_{L_E}}{C_{D_0}+KC_{L_E}^2} = \frac{\sqrt{\frac{C_{D_0}}{K}}}{2C_{D_0}} = \sqrt{\frac{1}{4KC_{D_0}}}$$
    """
    )
    return


@app.cell
def _():
    _defaults.nav_footer(
        "FlightControls.py", "Flight Controls", "MinSpeed.py", "Minimum Speed"
    )
    return


if __name__ == "__main__":
    app.run()
