import marimo

__generated_with = "0.13.6"
app = marimo.App(width="medium")

with app.setup:
    # Initialization code that runs before all other cells
    import marimo as mo
    import _defaults

    _defaults.set_plotly_template()


@app.cell
def _():
    _defaults.set_sidebar()
    return


@app.cell
def _():
    mo.md(r"""# Flight Constraints""")
    return


@app.cell
def _():
    mo.md(
        r"""
    ## Flight Mechanics


    In order to Analyse and Optimize the Flight Performance of an aircraft, it is first necessary to be able to _describe_ the motion of the aircraft itself.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    Flight Mechanics is the branch of aeronautics that describes the motion of an aircraft as a result of the forces and moments acting on it.  

    It explains the evolution of all flight parameters in terms of how these forces and moments are generated by the aircraft, and prescribes appropriate flight strategies to make the aircraft achieve desired performance.
    """
    ).callout(kind="success").style({"width": "75%", "text-align": "center"}).center()
    return


@app.cell
def _():
    mo.md(
        r"""
    The motion of the aircraft is described by a set of Ordinary Differential Equations (ODEs), commonly referred to as the_ Equations of Motion (EoMs)_. 

    The EoMs are derived from Newton's second law of dynamics, and can take different forms depending on🥇

    - which reference frame is used to represent them, and 
    - which assumptions are made to describe the motion to sufficient accuracy.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    ### Assumptions

    Within a FPAO problem, it is sufficient to describe the _position_, _translational velocity_, and _translational acceleration_ of the aircraft with respect to the air or ground.  
    It is therefore typical to regard the aircraft as a point-mass, with no actual geometry,  inertia, _orientation_, _angular velocity_ and _angular acceleration_ with respect to the air or the ground.

    This is done by modelling all external (aerodynamic, propulsive, inertial) forces as acting in one single point, the aircraft Center of gravity (CG), which becomes then representative of the aircraft motion.  

    A point-mass can have at most 3 Degrees of Freedom (DoFs), which correspond to the three translations it can have with respect to the air or the ground.  


    Moreover, regarding the external forces acting on the aircraft, it is going to be assumed that:

    1. The thrust force $\overrightarrow{T}$ is always aligned with the airspeed vector $\overrightarrow{V}$

    2. The pilot is able to fly so that the only aerodynamic force perpendicular to the airspeed vector $\overrightarrow{V}$ is lift.

    The latter assumption implies that turning flight is always executed in a _coordinated_ way, meaning that there is no sideslip angle between the aircraft body and the airspeed vector, hence the lift $\overrightarrow{L}$ and drag $\overrightarrow{D}$ forces act in the symmetry plane of the aircraft, and therefore there is no additional aerodynamic side force.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    ### Equations of Motion (EoMs)

    The most generic set of EoMs, for a point-mass aircraft in accelerated flight with 3 DoFs and constant mass, are  written with respect to the asymptotic airflow as:

    $$
    \begin{cases}
        m\dot{V}=T-D-W\sin{\gamma} \\
        mV\dot{\gamma}=L\cos{\mu}-W\cos{\gamma} \\
        mV\dot{\chi}\cos{\gamma}=L\sin{\mu} \\
    \end{cases}
    $$  

    They can be specialized in the following ways by making more stringent assumptions on the flight strategy or piloting technique:
    """
    )
    return


@app.cell
def _():
    mo.accordion(
        {
            "Accelerated Symmetric Flight": mo.md(
                r"""
                $$
                \begin{cases}
                    \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    m\dot{V} = T-D-W\sin{\gamma}\\
                    mV\dot{\gamma} = L-W\cos{\gamma}
                \end{cases}
                $$            
                """
            ).center(),
            "Accelerated Symmetric Rectilinear Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \gamma = \mathit{const} \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    m\dot{V} = T-D-W\sin{\gamma}\\
                    0 = L-W\cos{\gamma}
                \end{cases}
                $$            
                """
            ).center(),
            "Accelerated Symmetric Horizontal Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{\chi} = \dot{\gamma} =0 \\
                    \chi = \mathit{const} \\
                    \mu = 0 \\
                    \gamma = 0
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    m\dot{V} = T-D\\
                    0 = L - W
                \end{cases}
                $$            
                """
            ).center(),
            "Steady Symmetric Rectilinear Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{V} = \dot{\gamma} = \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \gamma = \mathit{const} \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    0 = T-D-W\sin{\gamma}\\
                    0 = L-W\cos{\gamma}
                \end{cases}
                $$            
                """
            ).center(),
            "Steady Symmetric Horizontal Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{V} = \dot{\gamma} = \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \gamma = 0 \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    0 = T-D\\
                    0 = L-W
                \end{cases}
                $$            
                """
            ).center(),
            "Steady Horizontal Coordinated Turn": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{V} = \dot{\gamma} = 0 \\
                    \dot{\chi} = \mathit{const} \\
                    \mu = \mathit{const} \\
                    \gamma = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    0 = T-D\\
                    0 = L\cos{\mu}-W \\
                    mV\dot{\chi}_0 = L\sin{\mu} \\
                \end{cases}
                $$            
                """
            ).center(),
        },
        multiple=True,
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    In case it is significant to take into account the change of mass of the aircraft, the following EoM should be appended to any of the previous systems of equations: 

    $$\dot{W} = -F$$
    """
    )
    return


@app.cell
def _():
    mo.md(r"""
    The Equations of Motion represent the most important physical constraint of the FPAO problem.  
    They are _equality constraints_ which regulate how all flight parameters should be related to each other to satisfy Newton's second law.
    """).callout(kind="success").style(
        {"width": "85%", "text-align": "center"}
    ).center()
    return


@app.cell
def _():
    mo.md(
        r"""
    ## Operations and safety

    Other types of equality or inequality constraints, typically coming from regulations and safety requirements, influence the FPAO problem.

    Some examples are:

    | <div style="width:500px">Prescription</div> | <div style="width:100px">Constraint</div> | <div style="width:100px">Constraint type</div>
    |:----|:----|:----|
    | Do not exceed the Maximum Operative Airspeed $V_\mathrm{MO}$ |  $V \le V_\mathrm{MO}$ | Inequality |
    | Do not exceed the Maximum Operative Mach number $M_\mathrm{MO}$ |  $M \le M_\mathrm{MO}$ |  Inequality |
    | Do not exceed the limit load factors $n_\mathrm{lim}^+$ and $n_\mathrm{lim}^-$ |  $n_\mathrm{lim}^- \le n\le n_\mathrm{lim}^+$ |  Inequality |
    | Descend along the glideslope |  $\gamma = -\gamma_\mathrm{gs}$ | Equality
    | Fly a cruise segment at constant altitude |  $h = \mathit{const}$ | Equality
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    Some of these constraints may be automatically verified by assumptions made on the EoMs.  
    In these cases, the constraint equations shape the motion of the aircraft already implictly, and do not need to be appended to FPAO problem formulation, as they would be redundant.

    For example, the EoMs for horizontal flight alredy implicitly constrain the motion of the aircraft to happen at constant altitude.
    Th constraint equations imposing $\dot{\gamma}=0$ and $\gamma=0$ have already been used to constrain the motion of the aircraft. 
    There is no need to append the same constraint equation in the formulation of the optimization problem.
    """
    )
    return


@app.cell
def _():
    _defaults.nav_footer(
        "ProblemFormulation.py",
        "Problem Formulation",
        "FlightControls.py",
        "FlightControls",
    )
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
