# SPDX-FileCopyrightText: 2026 Carmine Varriale <C.varriale@tudelft.nl>
# SPDX-FileCopyrightText: 2026 Federico Angioni <F.angioni@student.tudelft.nl>
# SPDX-FileCopyrightText: 2026 Maarten van Hoven <M.B.vanHoven@tudelft.nl>
#
# SPDX-License-Identifier: Apache-2.0
import marimo

__generated_with = "0.13.15"
app = marimo.App(width="medium")

with app.setup:
    import sys
    from pathlib import Path

    sys.path.insert(0, str(Path.cwd()))

    # Initialization code that runs before all other cells
    import marimo as mo
    from core import _defaults

    _defaults.FILEURL = _defaults.get_url()

    _defaults.set_plotly_template()


@app.cell
def _():
    _defaults.set_sidebar()
    return


@app.cell
def _():
    mo.md(r"""# Flight Constraints""")
    return


@app.cell
def _():
    mo.md(
        r"""
    ## Flight Mechanics


    In order to Analyse and Optimize the Flight Performance of an aircraft, it is first necessary to be able to _describe_ the motion of the aircraft itself.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    Flight Mechanics is the branch of aeronautics that describes the motion of an aircraft as a result of the forces and moments acting on it.  

    It explains the evolution of all flight parameters in terms of how these forces and moments are generated by the aircraft, and prescribes appropriate flight strategies to make the aircraft achieve desired performance.
    """
    ).callout(kind="success").style({"width": "75%", "text-align": "center"}).center()
    return


@app.cell
def _():
    mo.md(
        r"""
    The motion of the aircraft is described by a set of Ordinary Differential Equations (ODEs), commonly referred to as the_ Equations of Motion (EoMs)_. 

    The EoMs are derived from Newton's second law of dynamics, and can take different forms depending on🥇

    - which reference frame is used to represent them, and 
    - which assumptions are made to describe the motion to sufficient accuracy.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    ### Assumptions

    Within a CAPO problem, it is sufficient to describe the _position_, _translational velocity_, and _translational acceleration_ of the aircraft with respect to the air or ground.  
    It is therefore typical to regard the aircraft as a point-mass, with no actual geometry,  inertia, _orientation_, _angular velocity_ and _angular acceleration_ with respect to the air or the ground.

    This is done by modelling all external (aerodynamic, propulsive, inertial) forces as acting in one single point, the aircraft Center of gravity (CG), which becomes then representative of the aircraft motion.  

    A point-mass can have at most 3 Degrees of Freedom (DoFs), which correspond to the three translations it can have with respect to the air or the ground.  


    Moreover, regarding the external forces acting on the aircraft, it is going to be assumed that:

    1. The thrust force $\overrightarrow{T}$ is always aligned with the airspeed vector $\overrightarrow{V}$

    2. The pilot is able to fly so that the only aerodynamic force perpendicular to the airspeed vector $\overrightarrow{V}$ is lift.

    The latter assumption implies that turning flight is always executed in a _coordinated_ way, meaning that there is no sideslip angle between the aircraft body and the airspeed vector, hence the lift $\overrightarrow{L}$ and drag $\overrightarrow{D}$ forces act in the symmetry plane of the aircraft, and therefore there is no additional aerodynamic side force.
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    ### Equations of Motion (EoMs)

    The most generic set of EoMs, for a point-mass aircraft in accelerated flight with 3 DoFs and constant mass, are  written with respect to the asymptotic airflow as:

    $$
    \begin{cases}
        m\dot{V}=T-D-W\sin{\gamma} \\
        mV\dot{\gamma}=L\cos{\mu}-W\cos{\gamma} \\
        mV\dot{\chi}\cos{\gamma}=L\sin{\mu} \\
    \end{cases}
    $$  

    They can be specialized in the following ways by making more stringent assumptions on the flight strategy or piloting technique:
    """
    )
    return


@app.cell
def _():
    mo.accordion(
        {
            "Accelerated Symmetric Flight": mo.md(
                r"""
                $$
                \begin{cases}
                    \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    m\dot{V} = T-D-W\sin{\gamma}\\
                    mV\dot{\gamma} = L-W\cos{\gamma}
                \end{cases}
                $$            
                """
            ).center(),
            "Accelerated Symmetric Rectilinear Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \gamma = \mathit{const} \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    m\dot{V} = T-D-W\sin{\gamma}\\
                    0 = L-W\cos{\gamma}
                \end{cases}
                $$            
                """
            ).center(),
            "Accelerated Symmetric Horizontal Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{\chi} = \dot{\gamma} =0 \\
                    \chi = \mathit{const} \\
                    \mu = 0 \\
                    \gamma = 0
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    m\dot{V} = T-D\\
                    0 = L - W
                \end{cases}
                $$            
                """
            ).center(),
            "Steady Symmetric Rectilinear Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{V} = \dot{\gamma} = \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \gamma = \mathit{const} \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    0 = T-D-W\sin{\gamma}\\
                    0 = L-W\cos{\gamma}
                \end{cases}
                $$            
                """
            ).center(),
            "Steady Symmetric Horizontal Flight": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{V} = \dot{\gamma} = \dot{\chi} = 0 \\
                    \chi = \mathit{const} \\
                    \gamma = 0 \\
                    \mu = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    0 = T-D\\
                    0 = L-W
                \end{cases}
                $$            
                """
            ).center(),
            "Steady Horizontal Coordinated Turn": mo.md(
                r"""

                $$
                \begin{cases}
                    \dot{V} = \dot{\gamma} = 0 \\
                    \dot{\chi} = \mathit{const} \\
                    \mu = \mathit{const} \\
                    \gamma = 0 \\
                \end{cases}
                \quad \Rightarrow \quad
                \begin{cases}
                    0 = T-D\\
                    0 = L\cos{\mu}-W \\
                    mV\dot{\chi}_0 = L\sin{\mu} \\
                \end{cases}
                $$            
                """
            ).center(),
        },
        multiple=True,
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    In case it is significant to take into account the change of mass of the aircraft, the following EoM should be appended to any of the previous systems of equations: 

    $$\dot{W} = -F$$
    """
    )
    return


@app.cell
def _():
    mo.md(r"""
    The Equations of Motion represent the most important physical constraint of the CAPO problem.  
    They are _equality constraints_ $\bm{c}_\mathrm{eq}$ which regulate how all flight parameters should be related to each other to satisfy Newton's second law.
    """).callout(kind="success").style(
        {"width": "85%", "text-align": "center"}
    ).center()
    return


@app.cell
def _():
    mo.md(
        r"""
    ## Operations and safety

    Other types of equality or inequality constraints, typically coming from regulations and safety requirements, influence the CAPO problem.

    Some examples are:

    | <div style="width:500px">Prescription</div> | <div style="width:100px">Constraint</div> | <div style="width:100px">Constraint type</div>
    |:----|:----|:----|
    | Do not exceed the Maximum Operative Airspeed $V_\mathrm{MO}$ |  $V \le V_\mathrm{MO}$ | Inequality |
    | Do not exceed the Maximum Operative Mach number $M_\mathrm{MO}$ |  $M \le M_\mathrm{MO}$ |  Inequality |
    | Do not exceed the limit load factors $n_\mathrm{lim}^+$ and $n_\mathrm{lim}^-$ |  $n_\mathrm{lim}^- \le n\le n_\mathrm{lim}^+$ |  Inequality |
    | Descend along the glideslope |  $\gamma = -\gamma_\mathrm{gs}$ | Equality
    | Fly a cruise segment at constant altitude |  $h = \mathit{const}$ | Equality
    """
    )
    return


@app.cell
def _():
    mo.md(
        r"""
    ## Equality constraints

    Equality constraints may be manipulated by _substituting_ their expressions anywhere else in the optimization problem.
    This is also true for the EoMs constraints themselves.
    Equality constraints which are _explicit_ in any variable of interest may even be _directly eliminated_ from the optimization problem formulation.
    This can lead to great simplifications in the analysis of a parametric CAPO problem.

    For example, compare the following two sets of constraints:
    """
    )
    return


@app.cell
def _():
    mo.hstack(
        [
            mo.md(
                r"""
            $$
            \begin{cases}
                m\dot{V}=T-D-W\sin{\gamma} \\
                mV\dot{\gamma}=L\cos{\mu}-W\cos{\gamma} \\
                mV\dot{\chi}\cos{\gamma}=L\sin{\mu} \\
                \mu = 0 \\
                \dot{V} = 0
            \end{cases}
            $$  
            """
            ),
            mo.md(
                r"""
            $$
            \begin{cases}
                0=T-D-W\sin{\gamma} \\
                mV\dot{\gamma}=L-W\cos{\gamma} \\
                \dot{\chi}\cos{\gamma}=0 \\
            \end{cases}
            $$  
            """
            ),
        ],
        justify="center",
        align="center",
        widths="equal",
        gap=0,
    ).style({"width": "50%"}).center()
    return


@app.cell
def _():
    mo.md(
        r"""
    For the case on the left, the aircraft is free to evolve in 3 DoF, but we are only interested in its performance with no roll angle and in steady flight. This means that, in the CAPO problem, we are inspecting all possible dynamic evolutions of the aicraft and then searching for those that comply with these two latter constraints.

    For the case on the right, the aircraft is free to evolve only in the way that automatically verifies the intended scenario. 
    The two aforementioned equality constraints have been made _redundant_ by _direct substitution_, and therefore eliminated.

    The formulation is already much more prone to analysis and inspection.
    For example, the latter equation suggests that the type of evolution in exam is either a horizontal steady turn ($\gamma=0$), or symmetric curvlinear flight ($\dot{\chi}=0$). 


    These latter two equality constraints, which are mutually exclusive, may even be used to _branch_ and further simplify the CAPO problem in an iterative fashion.
    """
    )
    return


@app.cell
def _():
    _defaults.nav_footer(
        "Problem_Formulation/PointPerformance.py",
        "Point Performance",
        "Problem_Formulation/FlightControls.py",
        "Flight Controls",
    )
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
