name: Build, Export, and Deploy Marimo WASM Notebook

on:
  push:


env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install uv package manager for faster Python package installation
      - name: 🚀 Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt marimo build setuptools wheel plotly
    

      - name: 🛠️ Export notebooks
        run: |
          uv run .github/scripts/build.py --output-dir _site

      - name: Build core wheel and copy to _site/
        run: |
          python -m build -w notebooks
          mkdir -p _site/notebooks/public
          cp notebooks/dist/*.whl _site/notebooks/public
          cp requirements.txt _site/notebooks/public

          # Move everything (including hidden files) inside _site/notebooks to _site/
          rsync -a _site/notebooks/ _site/

          # Remove the _site/notebooks directory completely
          rm -rf _site/notebooks

          tree _site

                
      # Upload the generated site as an artifact for the deploy job
      - name: 📤 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
